# Generated by Django 5.1.15 on 2026-05-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0002_utf8mb4'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='codegenaudit',
            new_name='codegen_cod_status_ec8dc9_idx',
            old_name='codegen_status_created_idx',
        ),
    ]
