# Generated by Django 5.1.15 on 2026-04-18 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identificador único. Ej: 'daily', 'inventory', 'schedules'.", unique=True)),
                ('name', models.CharField(help_text="Nombre visible. Ej: 'Daily Log'.", max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('frontend_url', models.CharField(blank=True, help_text='URL base del frontend de esta herramienta.', max_length=500)),
                ('icon', models.CharField(blank=True, help_text="Nombre del ícono o clase CSS. Ej: 'fa-calendar'.", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'db_table': 'platform_tools',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserToolAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(db_column='tool_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='platform.tool')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='tool_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso de usuario a herramienta',
                'verbose_name_plural': 'Accesos de usuarios a herramientas',
                'db_table': 'platform_user_tool_access',
                'unique_together': {('user', 'tool')},
            },
        ),
    ]
