# Generated by Django 5.1.15 on 2026-08-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTokenEpoch',
            fields=[
                ('daily_user_id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('revoked_since', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Revocación de tokens (daily/platform)',
                'verbose_name_plural': 'Revocaciones de tokens (daily/platform)',
                'db_table': 'daily_token_epoch',
            },
        ),
    ]
