# Generated by Django 5.1.15 on 2026-05-22 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0001_add_sig_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('app', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'app_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'app_role_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAppRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
            ],
            options={
                'db_table': 'user_app_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteDeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.BigIntegerField(db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'site_device_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteDeviceDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.BigIntegerField(db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=50)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('qty_sent', models.IntegerField(blank=True, null=True)),
                ('tracking', models.CharField(blank=True, default='', max_length=500)),
                ('observations', models.TextField(blank=True, default='')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('qty_received', models.IntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_notes', models.TextField(blank=True, default='')),
                ('receipt_photo_url', models.TextField(blank=True, default='')),
                ('installed', models.BooleanField(default=False)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('install_notes', models.TextField(blank=True, default='')),
                ('install_photo_url', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_device_dispatch',
                'unique_together': {('site_id', 'device_id')},
            },
        ),
    ]
