# Generated by Django 5.1.15 on 2026-04-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('sub', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('Perifericos', 'Periféricos'), ('Electrodomesticos', 'Electrodomésticos'), ('Mobiliario', 'Mobiliario'), ('Computadores', 'Computadores'), ('Partes Electronicas', 'Partes Electrónicas')], max_length=50)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('reparado', 'Reparado'), ('reparacion', 'En reparación'), ('danado', 'Dañado')], default='activo', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('serial', models.CharField(blank=True, default='', max_length=200)),
                ('modified_by', models.CharField(blank=True, default='', max_length=100)),
                ('latest_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inv_articles',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_name', models.CharField(blank=True, default='Package', max_length=50)),
                ('color', models.CharField(blank=True, default='#6366f1', max_length=30)),
            ],
            options={
                'db_table': 'inv_groups',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='inventory.article')),
            ],
            options={
                'db_table': 'inv_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='inventory.group'),
        ),
    ]
