# Generated by Django 5.1.15 on 2026-05-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='checklist_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='checklist_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='checklist_received',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='observations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='quantity_send',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='tracking',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('reparado', 'Reparado'), ('reparacion', 'En reparación'), ('danado', 'Dañado'), ('cotizacion', 'En Cotización'), ('instalacion', 'En Instalación')], default='activo', max_length=20),
        ),
    ]
