# Generated by Django 5.1.15 on 2026-06-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cablerun',
            index=models.Index(fields=['site_id'], name='inv_cable_r_site_id_abe6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentreturn',
            index=models.Index(fields=['site_id'], name='inv_equipme_site_id_22168b_idx'),
        ),
    ]
