# Generated by Django 5.1.15 on 2026-06-01 02:52
# Modified to use IF NOT EXISTS so the migration is idempotent across environments

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS inv_cable_r_site_id_abe6a9_idx ON inventory_cablerun (site_id);",
                    reverse_sql="DROP INDEX IF EXISTS inv_cable_r_site_id_abe6a9_idx ON inventory_cablerun;",
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS inv_equipme_site_id_22168b_idx ON inventory_equipmentreturn (site_id);",
                    reverse_sql="DROP INDEX IF EXISTS inv_equipme_site_id_22168b_idx ON inventory_equipmentreturn;",
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='cablerun',
                    index=models.Index(fields=['site_id'], name='inv_cable_r_site_id_abe6a9_idx'),
                ),
                migrations.AddIndex(
                    model_name='equipmentreturn',
                    index=models.Index(fields=['site_id'], name='inv_equipme_site_id_22168b_idx'),
                ),
            ],
        ),
    ]
