# Generated by Django 5.1.15 on 2026-06-01 02:52
# Modified to be idempotent: skips index creation if table does not exist

from django.db import migrations, models


def add_indexes_if_tables_exist(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("SHOW TABLES LIKE 'inventory_cablerun'")
        if cursor.fetchone():
            cursor.execute(
                "SELECT COUNT(*) FROM information_schema.STATISTICS "
                "WHERE table_schema = DATABASE() AND table_name = 'inventory_cablerun' "
                "AND index_name = 'inv_cable_r_site_id_abe6a9_idx'"
            )
            if cursor.fetchone()[0] == 0:
                cursor.execute(
                    "CREATE INDEX inv_cable_r_site_id_abe6a9_idx ON inventory_cablerun (site_id)"
                )

        cursor.execute("SHOW TABLES LIKE 'inventory_equipmentreturn'")
        if cursor.fetchone():
            cursor.execute(
                "SELECT COUNT(*) FROM information_schema.STATISTICS "
                "WHERE table_schema = DATABASE() AND table_name = 'inventory_equipmentreturn' "
                "AND index_name = 'inv_equipme_site_id_22168b_idx'"
            )
            if cursor.fetchone()[0] == 0:
                cursor.execute(
                    "CREATE INDEX inv_equipme_site_id_22168b_idx ON inventory_equipmentreturn (site_id)"
                )


def remove_indexes_if_exist(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("SHOW TABLES LIKE 'inventory_cablerun'")
        if cursor.fetchone():
            cursor.execute(
                "SELECT COUNT(*) FROM information_schema.STATISTICS "
                "WHERE table_schema = DATABASE() AND table_name = 'inventory_cablerun' "
                "AND index_name = 'inv_cable_r_site_id_abe6a9_idx'"
            )
            if cursor.fetchone()[0] > 0:
                cursor.execute("DROP INDEX inv_cable_r_site_id_abe6a9_idx ON inventory_cablerun")

        cursor.execute("SHOW TABLES LIKE 'inventory_equipmentreturn'")
        if cursor.fetchone():
            cursor.execute(
                "SELECT COUNT(*) FROM information_schema.STATISTICS "
                "WHERE table_schema = DATABASE() AND table_name = 'inventory_equipmentreturn' "
                "AND index_name = 'inv_equipme_site_id_22168b_idx'"
            )
            if cursor.fetchone()[0] > 0:
                cursor.execute("DROP INDEX inv_equipme_site_id_22168b_idx ON inventory_equipmentreturn")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_indexes_if_tables_exist, remove_indexes_if_exist),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='cablerun',
                    index=models.Index(fields=['site_id'], name='inv_cable_r_site_id_abe6a9_idx'),
                ),
                migrations.AddIndex(
                    model_name='equipmentreturn',
                    index=models.Index(fields=['site_id'], name='inv_equipme_site_id_22168b_idx'),
                ),
            ],
        ),
    ]

