# Generated by Django 5.1.15 on 2026-07-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_cablerun_inv_cable_r_site_id_abe6a9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSpecChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_model_id', models.PositiveIntegerField(db_index=True)),
                ('rango_lente_mm', models.JSONField()),
                ('rango_fov_grados', models.JSONField()),
                ('changed_by_id', models.BigIntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inv_camera_spec_change_log',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['camera_model_id'], name='inv_camspec_model_idx')],
            },
        ),
    ]
