# Generated by Django 5.1.15 on 2026-04-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('session_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=100)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_audit_log',
                'managed': True,
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='daily_audit_user_id_0c6dc6_idx'), models.Index(fields=['action', '-created_at'], name='daily_audit_action_652670_idx'), models.Index(fields=['-created_at'], name='daily_audit_created_88ce71_idx')],
            },
        ),
    ]
