# Generated by Django 5.1.15 on 2026-04-18 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # ---- Real DB operations (match actual slc_schedules state) ----
            database_operations=[
                # The old unique constraint on sch_schedules only covers shift_date (no employee_id col)
                migrations.RunSQL(
                    sql="ALTER TABLE `sch_schedules` DROP INDEX `uq_sch_employee_shift_date`;",
                    reverse_sql="ALTER TABLE `sch_schedules` ADD UNIQUE KEY `uq_sch_employee_shift_date` (`shift_date`);",
                ),
                # Add user_id to sch_schedules
                migrations.RunSQL(
                    sql="ALTER TABLE `sch_schedules` ADD COLUMN `user_id` bigint NOT NULL DEFAULT 1;",
                    reverse_sql="ALTER TABLE `sch_schedules` DROP COLUMN `user_id`;",
                ),
                # Add user_id to sch_cancellation_requests
                migrations.RunSQL(
                    sql="ALTER TABLE `sch_cancellation_requests` ADD COLUMN `user_id` bigint NOT NULL DEFAULT 1;",
                    reverse_sql="ALTER TABLE `sch_cancellation_requests` DROP COLUMN `user_id`;",
                ),
                # Add user_id to sch_slot_claims
                migrations.RunSQL(
                    sql="ALTER TABLE `sch_slot_claims` ADD COLUMN `user_id` bigint NOT NULL DEFAULT 1;",
                    reverse_sql="ALTER TABLE `sch_slot_claims` DROP COLUMN `user_id`;",
                ),
                # Add target_user_id to sch_app_notifications (nullable)
                migrations.RunSQL(
                    sql="ALTER TABLE `sch_app_notifications` ADD COLUMN `target_user_id` bigint NULL;",
                    reverse_sql="ALTER TABLE `sch_app_notifications` DROP COLUMN `target_user_id`;",
                ),
                # Add new unique constraint on (user_id, shift_date)
                migrations.RunSQL(
                    sql="ALTER TABLE `sch_schedules` ADD CONSTRAINT `uq_sch_user_shift_date` UNIQUE (`user_id`, `shift_date`);",
                    reverse_sql="ALTER TABLE `sch_schedules` DROP INDEX `uq_sch_user_shift_date`;",
                ),
                # Drop the sch_employees table entirely
                # NOTE: If app_user lacks DROP privilege, comment out the RunSQL below
                # and ask a DBA to run: DROP TABLE sch_employees;
                # migrations.RunSQL(
                #     sql="DROP TABLE IF EXISTS `sch_employees`;",
                #     reverse_sql="",
                # ),
            ],
            # ---- Django state operations (sync model state) ----
            state_operations=[
                migrations.RemoveField(model_name='appnotification', name='target_employee'),
                migrations.RemoveField(model_name='cancellationrequest', name='employee'),
                migrations.RemoveField(model_name='slotclaim', name='employee'),
                migrations.RemoveConstraint(model_name='schedule', name='uq_sch_employee_shift_date'),
                migrations.RemoveField(model_name='schedule', name='employee'),
                migrations.AddField(
                    model_name='appnotification',
                    name='target_user',
                    field=models.ForeignKey(blank=True, db_column='target_user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_notifications', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cancellationrequest',
                    name='user',
                    field=models.ForeignKey(db_column='user_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='schedule',
                    name='user',
                    field=models.ForeignKey(db_column='user_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedules', to=settings.AUTH_USER_MODEL),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='slotclaim',
                    name='user',
                    field=models.ForeignKey(db_column='user_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='slot_claims', to=settings.AUTH_USER_MODEL),
                    preserve_default=False,
                ),
                migrations.AddConstraint(
                    model_name='schedule',
                    constraint=models.UniqueConstraint(fields=('user', 'shift_date'), name='uq_sch_user_shift_date'),
                ),
                migrations.RemoveField(model_name='employee', name='squad'),
                migrations.DeleteModel(name='Employee'),
            ],
        ),
    ]
